version: '1.0'
services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
          # <Port on the host> : < Port inside the container (same as Dockerfile)>
            - '3000:3000'
        volumes:
          # mounts the dir on the host to the container, allowing you to modify the code on the fly
          # <(current)directory on the host> : < dir for container>
          - .:/usr/src/app
        restart: always      
        environment:        
          SESSION_SECRET: docker_cat
          SESSION_STORE: redis
          #Refer to the service name: redis
          REDIS_URL: 'redis://redis:6379'
    redis:
        image: "redis:alpine"
        restart: always
        ports:
          # <Port for hosts> : < Port for containers>
          - '6379:6379'

          